[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build:ts && pnpm prisma generate"

[deploy]
startCommand = "fastify start -l info -a 0.0.0.0 dist/src/app.js"
healthcheckPath = "/"
healthcheckTimeout = 100

